"""Scaffold an ``mdq.toml`` for a repository that does not have one yet.

Without a config file ``mdq`` falls back to ``GENERIC_DEFAULT_ROOTS``
(``docs`` / ``users-guide``). That is a safe default but it silently skips
every other documentation root, so the first index in a new repository is
often almost empty. This script proposes the roots that actually contain
Markdown.

The file walker is **not** re-implemented here; ``mdq.indexer.iter_markdown``
is used so the proposal can never drift from what the indexer really accepts.

Usage::

    python init_config.py --repo-root . --dry-run
    python init_config.py --repo-root .
    python init_config.py --repo-root . --force
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

_VENDOR = Path(__file__).resolve().parent / "vendor"
if _VENDOR.is_dir():
    sys.path.insert(0, str(_VENDOR))

try:
    from mdq.config import CONFIG_FILENAMES, GENERIC_DEFAULT_ROOTS
    from mdq.indexer import iter_markdown
except ImportError as exc:  # pragma: no cover - surfaced to the operator
    raise SystemExit(
        f"cannot import the mdq engine ({exc}). Run sync-vendor.ps1 / sync-vendor.sh "
        "first, or put the mdq package on PYTHONPATH."
    ) from exc

# Directories that hold dependencies or build output. Proposing them as roots
# would make the first mdq.toml a user sees wrong.
NOISY_TOP_LEVEL = frozenset({
    ".git", ".github", ".venv", "venv", "node_modules", "vendor", "third_party",
    "dist", "build", "out", "bin", "obj", "target", "coverage", "__pycache__",
    ".mdq", ".cq", ".idea", ".vscode",
})

TEMPLATE = """# mdq configuration for this repository.
#
# Generated by tools/skills/markdown_query/init_config.py.
# Schema reference: mdq/config.py in the upstream HVE repository.

[index]
roots = [
{roots}
]
"""


def propose_roots(repo_root: Path) -> list[tuple[str, int]]:
    """Return ``(root, markdown_file_count)`` for every promising top-level dir."""
    proposals: list[tuple[str, int]] = []
    for entry in sorted(repo_root.iterdir()):
        if not entry.is_dir() or entry.name in NOISY_TOP_LEVEL:
            continue
        count = sum(1 for _ in iter_markdown(repo_root, [entry.name]))
        if count:
            proposals.append((entry.name, count))
    return proposals


def render(roots: Sequence[str]) -> str:
    body = "\n".join(f'    "{root}",' for root in roots)
    return TEMPLATE.format(roots=body)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--force", action="store_true",
                        help="Overwrite an existing mdq.toml.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print the proposal without writing it.")
    args = parser.parse_args(argv)

    repo_root = args.repo_root.resolve()
    if not repo_root.is_dir():
        print(f"[markdown-query init] not a directory: {repo_root}", file=sys.stderr)
        return 2

    existing = [repo_root / name for name in CONFIG_FILENAMES]
    present = [p for p in existing if p.is_file()]
    target = repo_root / CONFIG_FILENAMES[0]
    if present and not args.force and not args.dry_run:
        print(f"[markdown-query init] {present[0]} already exists; keeping it "
              "(use --force to regenerate).")
        return 0

    proposals = propose_roots(repo_root)
    roots = [name for name, _ in proposals] or list(GENERIC_DEFAULT_ROOTS)
    content = render(roots)

    for name, count in proposals:
        print(f"[markdown-query init] {name}/: {count} markdown file(s)")
    if not proposals:
        print("[markdown-query init] no markdown found; falling back to "
              f"{GENERIC_DEFAULT_ROOTS}")

    if args.dry_run:
        print(content)
        return 0

    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"[markdown-query init] wrote {target}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
