import {state,setModel,items} from "./store.js";
import {toggleLanguage,t} from "./i18n.js";
import {renderTables} from "./tables.js";
import {renderSource} from "./source.js";
const view=document.querySelector("#view"), q=document.querySelector("#q"), results=document.querySelector("#results"), toast=document.querySelector("#toast");
const base=location.href.split("#")[0];
async function load(path="/api/model"){const r=await fetch(path);const data=await r.json();if(!r.ok)throw Error(data.error||"data error");setModel(data);document.querySelector("#repoBtn").textContent=data.repo;return data;}
function route(){const [raw,query]=""+location.hash.slice(2).split("?");const params=new URLSearchParams(query);state.query=params.get("q")||q.value||"";state.selected=params.get("select");if(raw==="tables"||!raw){renderTables(view);}else if(raw==="source"){renderSource(view);}else if(raw==="dashboard"){view.innerHTML=`<h1>Dashboard</h1><div class="grid">${["要求","目的","境界","Product"].map(x=>`<div class="card"><h2>${x}</h2><span class="link" onclick="location.hash='#/map2d'">${x==="要求"?items().length:"G-001"}</span></div>`).join("")}</div>`;}else{view.innerHTML=`<h1>${raw}</h1><div class="card">${state.selected||"G-001"}<p>Relationships and visual representation</p></div>`;}if(state.selected)selectItem(state.selected,true);}
function selectItem(id,silent=false){state.selected=id;const x=items().find(v=>v.id===id);document.querySelector("#drawer").innerHTML=`<button id="close">Close</button><h2>${id}</h2><p>${x?.text||id}</p><p>AC: ${x?.acs?.map(a=>a.id).join(", ")||""}</p><p>catalog: ${x?.catalog?.files||"EABK-Studio"} test: ${x?.catalog?.tests||"test"} SRC-001</p>`;document.querySelector("#drawer").classList.remove("hidden");document.querySelector("#close").onclick=()=>document.querySelector("#drawer").classList.add("hidden");if(!silent)location.hash=`#/map2d?select=${encodeURIComponent(id)}`;}
window.selectItem=selectItem;
function search(){state.query=q.value;results.innerHTML=items().filter(x=>JSON.stringify(x).toLowerCase().includes(state.query.toLowerCase())).slice(0,40).map(x=>`<div class="link" data-id="${x.id}">${x.id} ${x.title}</div>`).join("");results.classList.toggle("hidden",!state.query);results.querySelectorAll("[data-id]").forEach(e=>e.onclick=()=>selectItem(e.dataset.id));}
q.oninput=search;q.onkeydown=e=>{if(e.key==="Enter"&&q.value){const x=items().find(x=>x.id.toLowerCase()===q.value.toLowerCase())||items().find(x=>JSON.stringify(x).toLowerCase().includes(q.value.toLowerCase()));if(x)selectItem(x.id);}};document.addEventListener("keydown",e=>{if(e.key==="/"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();q.focus();}if(e.ctrlKey&&e.key.toLowerCase()==="k"){e.preventDefault();q.focus();}});
document.querySelector("#langBtn").onclick=toggleLanguage;window.addEventListener("languagechange",()=>{document.querySelector("#langBtn").textContent=window.__lang==="en"?"JA":"EN";route();});
document.querySelector("#repoBtn").onclick=()=>{const d=document.querySelector("#repoDialog");document.querySelector("#repoPath").value=state.model?.repo_path||"";d.showModal();};
document.querySelector("#repoCancel").onclick=()=>document.querySelector("#repoDialog").close();
document.querySelector("#repoOk").onclick=async()=>{try{const r=await fetch("/api/repo",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path:document.querySelector("#repoPath").value})});const data=await r.json();if(!r.ok)throw Error(data.error);setModel(data);document.querySelector("#repoDialog").close();route();}catch(e){toast.textContent=e.message;toast.classList.remove("hidden");setTimeout(()=>toast.classList.add("hidden"),4000);}};
async function refresh(){try{const r=await fetch("/api/fingerprint");const x=await r.json();if(state.fingerprint&&state.fingerprint!==x.fingerprint){await load();toast.textContent=t("updated");toast.classList.remove("hidden");route();}state.fingerprint=x.fingerprint;}catch(_){}}
window.addEventListener("hashchange",route);load().then(route);setInterval(refresh,4000);
