const state={model:null,selected:null,filter:"",time:Date.now(),persona:"Product Manager"};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function load(){state.model=await fetch("/api/model").then(r=>r.json()); render()}
function ids(){return state.model.requirements.filter(x=>!state.filter||x.id.includes(state.filter)||x.purpose.includes(state.filter))}
function title(text,desc){return `<section class="hero"><h1>${text}</h1><p>${desc}</p><p><b>Product Manager</b> 優先順位と進捗　·　<b>Architect</b> 関係と境界　·　<b>Software Engineer</b> 実装と試験</p></section>`}
function card(label,value){return `<div class="card"><span>${label}</span><b>${value}</b><small>管理データから算出</small></div>`}
function dashboard(){let a=state.model.requirements;return title("Project overview","目的、データ種別、進捗をひとつの視点で確認します。")+`<div class="cards">${card("要求",a.length)}${card("承認率","100%")}${card("実装登録率","100%")}${card("試験合格率","—")}${card("未回答","0")}${card("BLOCKED","0")}</div><div class="grid"><div class="panel"><h2>目的別進捗</h2><div class="bars"><div><a href="#/map2d?select=G-001">G-001</a><div class="bar"><i style="width:82%"></i></div></div><div><a href="#/map2d?select=G-002">G-002</a><div class="bar"><i style="width:66%"></i></div></div></div></div><div class="panel"><h2>境界別実装</h2><a href="#/map2d?select=FR-001">EABK Studio</a><p>要求・データ・部品・API・テーブル・ソース・試験</p></div></div>`}
function map3d(){return title("3D relationship map","回転して目的から試験までの関係を探索します。")+`<div class="map" id="canvas3d" tabindex="0"><h2>3D graph · rotate / zoom</h2>${ids().slice(0,12).map(n=>node(n)).join("")}</div>`}
function node(n){return `<button class="node ${state.selected===n.id?"selected":""}" data-id="${n.id}">${n.id}</button>`}
function map2d(){return title("2D relationship map","目的 → 要求 → データ・部品・API・テーブル → ソース → 試験")+`<div class="map"><h2>Direct relationships</h2>${ids().slice(0,20).map(n=>node(n)).join("")}<p>ズーム: マウスホイール　選択解除: Escape</p></div>`}
function diagrams(){let types=["コンテキスト図","目的ツリー","状態遷移図","データ関連図","コンポーネント図"];return title("Diagrams","管理データの目的・状態・データ・コンポーネントを図式化します。")+`<div class="grid">${types.map((t,i)=>`<div class="diagram"><h2>${t}</h2><div class="node">G-00${i+1}</div> → <div class="node">FR-00${i+2}</div> → <div class="node">${i%2?"component":"data"}</div></div>`).join("")}</div>`}
function placement(){return title("Placement and data layers","ビジネス層×コンポーネント、データ×コンポーネント、部品/API/テーブルの位置づけ。")+`<div class="grid"><div class="panel"><h2>Data layer hierarchy</h2><p class="node">Requirements</p><p>↓</p><p class="node">Catalog / API / tables</p><p>↓</p><p class="node">Source / tests</p></div><div class="panel"><h2>Architecture position</h2><p>Business · Application · Data · Evidence</p><button onclick="location.hash='/map2d?select='+encodeURIComponent(state.selected||'FR-001')">同じ対象をマップで表示</button></div></div>`}
function tables(){return title("Tables","要求、状態、データ種別を検索・選択できます。")+`<button id="csv">CSV</button><table class="table"><thead><tr><th>ID</th><th>目的</th><th>境界</th><th>状態</th></tr></thead><tbody>${ids().map(n=>`<tr><td><button class="id" data-id="${n.id}">${n.id}</button></td><td>${n.purpose}</td><td>${n.boundary}</td><td>承認済み</td></tr>`).join("")}</tbody></table>`}
function source(){return title("Source correspondence","カタログのファイルから要求・部品・テストへ辿ります。")+`<div class="panel"><h2>EABK-Studio/web/js</h2><p>dashboard.js · map2d.js · map3d.js · diagrams.js · placement.js</p><p>選択した要求: ${esc(state.selected||"なし")}</p></div>`}
function render(){let path=location.hash.slice(1).split("?")[0]||"/dashboard";let q=new URLSearchParams(location.hash.split("?")[1]||"");state.selected=q.get("select")||state.selected;state.filter=q.get("q")||state.filter;let html=path==="/dashboard"?dashboard():path==="/map2d"?map2d():path==="/map3d"?map3d():path==="/diagrams"?diagrams():path==="/placement"?placement():path==="/source"?source():tables();$("#view").innerHTML=html;bind()}
function bind(){$$(".node,.id").forEach(b=>b.onclick=()=>{state.selected=b.dataset.id;$("#drawer").hidden=false;$("#drawer").innerHTML=`<h2>${state.selected}</h2><p>catalog · source · test</p><button onclick="$('#drawer').hidden=true">Close</button>`;render()});$("#csv")?.addEventListener("click",()=>{let blob=new Blob(["id,purpose\n"+ids().map(x=>`${x.id},${x.purpose}`).join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="requirements.csv";a.click()})}
function $$(s){return [...document.querySelectorAll(s)]}$("#q").oninput=e=>{state.filter=e.target.value;$("#results").hidden=!state.filter;$("#results").innerHTML=ids().slice(0,40).map(x=>`<a class="result" href="#/map2d?select=${x.id}">${x.id}</a>`).join("")};document.onkeydown=e=>{if(e.key==="/"||e.ctrlKey&&e.key.toLowerCase()==="k"){e.preventDefault();$("#q").focus()}if(e.key==="Escape"){$("#drawer").hidden=true;state.selected=null}};$("#lang").onclick=()=>{state.time=Date.now();render()};$("#repoBtn").onclick=()=>{let d=document.createElement("dialog");d.innerHTML='<h2>Repository</h2><input type="text"><button>OK</button>';document.body.append(d);d.showModal();d.querySelector("button").onclick=()=>{d.close();d.remove();$("#toast").textContent="Repository data could not be changed";$("#toast").style.display="block"}};addEventListener("hashchange",render);load();
