inputs:
- path: docs/catalog/use-case-catalog.md
  required: true
  kind: agent_artifact
  producer: Arch-ARD-UseCaseCatalog--ard--4.3
- path: docs/catalog/service-catalog.md
  required: true
  kind: agent_artifact
  producer: Arch-Microservice-ServiceIdentify--aas--3.2
- path: docs/services/{serviceId}-{serviceNameSlug}-description.md
  required: true
  kind: agent_artifact
  producer: Arch-Microservice-ServiceDetail--aad-web--2.2
- path: docs/catalog/app-catalog.md
  required: true
  kind: agent_artifact
  producer: Arch-ApplicationAnalytics--aas--1
- path: docs/azure/azure-services-compute.md
  required: true
  kind: agent_artifact
  producer: Dev-Microservice-Azure-ComputeDesign--asdw-web--2.1
- path: docs/azure/azure-services-data.md
  required: true
  kind: agent_artifact
  producer: Dev-Microservice-Azure-DataDesign--asdw-web--1.1
outputs:
- path: docs/azure/azure-services-additional.md
  required: true
  mode: append
