"""tools/fetch_xterm_assets.py — xterm.js 配布物を npm tarball から取得して
hve/gui/widgets/xterm_assets/vendor/ へ配置する。

実在する以下 2 パッケージを固定バージョンで取得する (捏造防止):
  - @xterm/xterm@6.0.0
  - @xterm/addon-fit@0.11.0

抽出する成果物:
  vendor/xterm/lib/xterm.js
  vendor/xterm/css/xterm.css
  vendor/xterm-addon-fit/lib/addon-fit.js
  vendor/VERSIONS.txt  (取得元 URL / バージョン / 取得日時)
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import io
import tarfile
import urllib.request
from pathlib import Path

PACKAGES = [
    {
        "name": "@xterm/xterm",
        "version": "6.0.0",
        "url": "https://registry.npmjs.org/@xterm/xterm/-/xterm-6.0.0.tgz",
        "extract": {
            "package/lib/xterm.js": "xterm/lib/xterm.js",
            "package/lib/xterm.js.map": "xterm/lib/xterm.js.map",
            "package/css/xterm.css": "xterm/css/xterm.css",
            "package/LICENSE": "xterm/LICENSE",
        },
    },
    {
        "name": "@xterm/addon-fit",
        "version": "0.11.0",
        "url": "https://registry.npmjs.org/@xterm/addon-fit/-/addon-fit-0.11.0.tgz",
        "extract": {
            "package/lib/addon-fit.js": "xterm-addon-fit/lib/addon-fit.js",
            "package/lib/addon-fit.js.map": "xterm-addon-fit/lib/addon-fit.js.map",
            "package/LICENSE": "xterm-addon-fit/LICENSE",
        },
    },
]

VENDOR_DIR = Path(__file__).resolve().parent.parent / "hve" / "gui" / "widgets" / "xterm_assets" / "vendor"


def fetch_and_extract() -> None:
    VENDOR_DIR.mkdir(parents=True, exist_ok=True)
    versions_lines: list[str] = [
        f"# Generated by tools/fetch_xterm_assets.py at {_dt.datetime.utcnow().isoformat()}Z",
        "",
    ]
    for pkg in PACKAGES:
        print(f"Fetching {pkg['name']}@{pkg['version']}...")
        with urllib.request.urlopen(pkg["url"], timeout=60) as resp:  # noqa: S310 - npm registry
            data = resp.read()
        digest = hashlib.sha256(data).hexdigest()
        print(f"  size={len(data)} sha256={digest}")
        with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as tf:
            for src, dst in pkg["extract"].items():
                try:
                    member = tf.getmember(src)
                except KeyError:
                    print(f"  WARN: {src} not found in tarball; skipping")
                    continue
                out_path = VENDOR_DIR / dst
                out_path.parent.mkdir(parents=True, exist_ok=True)
                fobj = tf.extractfile(member)
                if fobj is None:
                    continue
                out_path.write_bytes(fobj.read())
                print(f"  -> {out_path.relative_to(VENDOR_DIR.parent.parent.parent.parent)}")
        versions_lines.append(f"{pkg['name']}=={pkg['version']}")
        versions_lines.append(f"  url: {pkg['url']}")
        versions_lines.append(f"  sha256: {digest}")
        versions_lines.append("")
    (VENDOR_DIR / "VERSIONS.txt").write_text("\n".join(versions_lines), encoding="utf-8")
    print(f"\nWrote {VENDOR_DIR / 'VERSIONS.txt'}")


if __name__ == "__main__":
    fetch_and_extract()
